services:
  commercialbreaker:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - ENVIRONMENT=production
      - ANIME_FOLDER=/app/anime
      - BUMP_FOLDER=/app/bump
      - SPECIAL_BUMP_FOLDER=/app/special_bump
      - WORKING_FOLDER=/app/working
    volumes:
      - type: bind
        source: ${ANIME_FOLDER_PATH:-./data/anime}
        target: /app/anime
      - type: bind
        source: ${BUMP_FOLDER_PATH:-./data/bump}
        target: /app/bump
      - type: bind
        source: ${SPECIAL_BUMP_FOLDER_PATH:-./data/special_bump}
        target: /app/special_bump
      - type: bind
        source: ${WORKING_FOLDER_PATH:-./data/working}
        target: /app/working
      - type: bind
        source: ./ComBreak
        target: /app/ComBreak
        read_only: true
      - type: bind
        source: ./CLI
        target: /app/CLI
        read_only: true
      - type: bind
        source: ./GUI
        target: /app/GUI
        read_only: true
      - type: bind
        source: ./ToonamiTools
        target: /app/ToonamiTools
        read_only: true
      - type: bind
        source: ./Tools
        target: /app/Tools
        read_only: true
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5