"""
Unloading Dock - Where finished products are handed to clients.

Responsibilities:
1. FIFO Streaming - Manages background builder threads and FIFO pipes
2. Output Wrapper - Hands out playlists/guides generated by FactoryFloor

Input: Player requests for specific channel/metadata
Output: Continuous MPEG-TS streams, XMLTV guides, lineup.json

Architecture: See docs/FIFO-Architecture-Redesign.md
"""

import os
import subprocess
import threading
from pathlib import Path
from typing import Optional, TYPE_CHECKING

if TYPE_CHECKING:
    from .LoadingDock import LoadingDock

import config
from ..utilities.ExecutableUtils import get_executable_path
from ..utilities import get_audio_selector
from ..utilities.BroadcastTower import BroadcastTower


class UnloadingDock:
    """
    Manages FIFO-based continuous streaming for channels.

    Each channel gets:
    - One FIFO pipe (/tmp/combreak_ch<N>.fifo)
    - One background builder thread (transcodes programs, writes to FIFO)
    - Multiple client connections (each spawns a main FFmpeg reading from FIFO)
    """

    def __init__(self, loading_dock: "LoadingDock"):
        """Initialize UnloadingDock with reference to LoadingDock."""
        from .LoadingDock import LoadingDock
        self.loading_dock: LoadingDock = loading_dock
        self.factory_floor = loading_dock.factory_floor

        # Track active studios (builder threads) and broadcast towers
        self.active_studios = {}  # {channel_number: Thread} - Studio with full tape
        self.broadcast_towers = {}  # {channel_number: BroadcastTower} - Transmits live signal
        self.broadcast_ffmpegs = {}  # {channel_number: subprocess.Popen} - Broadcast FFmpeg processes
        self.studio_fifos = {}  # {channel_number: fifo_path} - FIFOs between studio and broadcast FFmpeg

        # Audio track selector
        self.audio_selector = get_audio_selector()

        # Cache FFmpeg path for Windows compatibility
        self.ffmpeg_bin = get_executable_path("ffmpeg", getattr(config, "ffmpeg_path", None))

        print("[UNLOADING_DOCK] Ready for multi-client streaming")

    # ============================================================================
    # BROADCAST TOWER MANAGEMENT
    # ============================================================================

    def create_broadcast_tower(self, channel_number: int) -> BroadcastTower:
        """
        Create BroadcastTower for channel.

        BroadcastTower provides:
        - Multi-client support (beams to all antennas)
        - NO buffering (only live signal)
        - Automatic disconnect detection

        Returns:
            BroadcastTower instance
        """
        tower = BroadcastTower()
        print(f"[UNLOADING_DOCK] Created BroadcastTower for channel {channel_number}")
        return tower

    def create_studio_fifo(self, channel_number: int) -> str:
        """
        Create FIFO pipe between studio and broadcast FFmpeg.

        Returns:
            Path to FIFO file
        """
        fifo_path = f'/tmp/studio_ch{channel_number}.fifo'

        # Remove existing FIFO if present
        if os.path.exists(fifo_path):
            try:
                os.remove(fifo_path)
            except OSError as e:
                print(f"[UNLOADING_DOCK] Warning: Could not remove existing FIFO: {e}")

        # Create new FIFO
        try:
            os.mkfifo(fifo_path)
            print(f"[UNLOADING_DOCK] Created studio FIFO: {fifo_path}")
        except OSError as e:
            print(f"[UNLOADING_DOCK] Error creating FIFO: {e}")
            raise

        return fifo_path

    def start_broadcast_ffmpeg(self, channel_number: int, fifo_path: str, broadcast_tower: BroadcastTower):
        """
        Start broadcast FFmpeg process that reads from studio FIFO and feeds BroadcastTower.

        This creates the continuous stream by using +genpts to flatten transitions.

        Args:
            channel_number: Channel number
            fifo_path: Path to studio FIFO
            broadcast_tower: BroadcastTower to feed chunks to
        """
        cmd = [
            self.ffmpeg_bin,
            '-hide_banner',
            '-loglevel', 'error',

            # Input from studio FIFO
            '-fflags', '+genpts+discardcorrupt',
            '-i', fifo_path,

            # Pass through (already normalized by studio)
            '-c', 'copy',

            # Output as MPEG-TS
            '-f', 'mpegts',
            '-muxdelay', '0',
            '-muxpreload', '0',
            'pipe:1'
        ]

        proc = subprocess.Popen(
            cmd,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE
        )

        self.broadcast_ffmpegs[channel_number] = proc
        print(f"[BROADCAST_FFMPEG] Ch{channel_number}: Started reading from {fifo_path}")

        # Start thread to read from broadcast FFmpeg and feed to tower
        def broadcast_reader():
            try:
                import time
                chunk_size = 188 * 50
                chunk_interval = 0.013  # 13ms per chunk (~5.4 Mbps)
                bytes_broadcast = 0
                last_broadcast_time = time.time()

                while True:
                    chunk = proc.stdout.read(chunk_size)
                    if not chunk:
                        break

                    # Only broadcast if tower has antennas
                    if broadcast_tower.has_antennas():
                        # Rate limit broadcasting to real-time
                        now = time.time()
                        time_since_last = now - last_broadcast_time
                        if time_since_last < chunk_interval:
                            time.sleep(chunk_interval - time_since_last)

                        broadcast_tower.broadcast(chunk)
                        last_broadcast_time = time.time()
                        bytes_broadcast += len(chunk)
                    else:
                        # No clients - stop this FFmpeg
                        print(f"[BROADCAST_FFMPEG] Ch{channel_number}: No clients, stopping")
                        proc.terminate()
                        break

                print(f"[BROADCAST_FFMPEG] Ch{channel_number}: Stopped ({bytes_broadcast / 1024 / 1024:.1f} MB broadcast)")
            except Exception as e:
                print(f"[BROADCAST_FFMPEG] Ch{channel_number}: Error - {e}")
            finally:
                # Clean up
                try:
                    proc.terminate()
                except:
                    pass
                if channel_number in self.broadcast_ffmpegs:
                    del self.broadcast_ffmpegs[channel_number]
                # Remove studio from active list so it can restart fresh next time
                if channel_number in self.active_studios:
                    del self.active_studios[channel_number]
                    print(f"[UNLOADING_DOCK] Cleaned up studio for channel {channel_number}")

        reader_thread = threading.Thread(target=broadcast_reader, daemon=True, name=f"BroadcastFFmpeg-Ch{channel_number}")
        reader_thread.start()

        return proc

    # ============================================================================
    # STUDIO THREAD (THE TAPE)
    # ============================================================================

    def build_stream(self, channel_data: dict, fifo_path: str):
        """
        Studio thread - continuously builds and writes MPEG-TS to FIFO.

        Like a TV studio with the full "tape":
        1. Calculate current position in channel (elapsed time since startTime)
        2. Find which program should be playing right now
        3. Spawn FFmpeg to transcode from correct position
        4. Write chunks to FIFO (feeds broadcast FFmpeg)
        5. Continue with subsequent programs, loop channel when reaching end

        On error: Write error screen and continue
        Studio runs continuously - stops only when channel deleted

        Args:
            channel_data: Channel configuration dict
            fifo_path: Path to FIFO to write to
        """
        from datetime import datetime, timezone

        programs = channel_data['programs']
        channel_number = channel_data['number']

        # Calculate where we should be in the channel RIGHT NOW using guide times
        now = datetime.now(timezone.utc)
        current_index = 0
        offset_in_first_program = 0

        # Find which program should be playing by checking guide start/stop times
        for i, prog in enumerate(programs):
            prog_start_str = prog.get('start')
            prog_stop_str = prog.get('stop')

            if not prog_start_str or not prog_stop_str:
                continue

            prog_start = datetime.fromisoformat(prog_start_str.replace('Z', '+00:00'))
            prog_stop = datetime.fromisoformat(prog_stop_str.replace('Z', '+00:00'))

            # Check if current time falls within this program's schedule
            if prog_start <= now < prog_stop:
                current_index = i
                # Calculate offset into this program
                offset_in_first_program = int((now - prog_start).total_seconds() * 1000)
                print(f"[STUDIO] Channel {channel_number}: Current time {now.strftime('%H:%M:%S')} falls in program #{current_index}")
                print(f"[STUDIO] Channel {channel_number}: Starting at program #{current_index} with {offset_in_first_program/1000:.1f}s offset")
                break
        else:
            # If current time doesn't match any program, find the next upcoming program
            # or loop back to the beginning
            future_programs = [(i, p) for i, p in enumerate(programs) if datetime.fromisoformat(p.get('start', '').replace('Z', '+00:00')) > now]
            if future_programs:
                current_index = future_programs[0][0]
                print(f"[STUDIO] Channel {channel_number}: Between programs, will start at next program #{current_index}")
            else:
                # All programs are in the past, loop back to beginning
                current_index = 0
                offset_in_first_program = 0
                print(f"[STUDIO] Channel {channel_number}: All programs in past, looping to program #0")

        print(f"[STUDIO] Channel {channel_number} studio thread starting")

        try:
            # Open FIFO for writing (unbuffered)
            with open(fifo_path, 'wb', buffering=0) as fifo:
                first_program = True
                while True:
                    # Publish the active index so background watchers (e.g. the
                    # infinite-channel LineupExtender) can read where the channel
                    # is right now without touching the studio thread.
                    channel_data.setdefault('_runtime', {})['current_index'] = current_index
                    program = programs[current_index % len(programs)]

                    # Calculate seek and duration
                    seek_ms = program.get('seekPosition', 0)
                    end_ms = program.get('endPosition', 0)
                    duration_ms = end_ms - seek_ms

                    # For the first program, apply the offset
                    if first_program and offset_in_first_program > 0:
                        seek_ms += offset_in_first_program
                        duration_ms -= offset_in_first_program
                        print(f"[STUDIO] Ch{channel_number}: Applying offset of {offset_in_first_program/1000:.1f}s to first program")

                    if duration_ms <= 0:
                        print(f"[STUDIO] Ch{channel_number}: Invalid duration for program #{current_index}, skipping")
                        current_index += 1
                        continue

                    file_path = program['file']
                    print(f"[STUDIO] Ch{channel_number} prog#{current_index}: {Path(file_path).name} @ {seek_ms/1000:.1f}s for {duration_ms/1000:.1f}s")

                    # Get audio track mapping for English audio
                    audio_mapping = self.audio_selector.get_ffmpeg_audio_mapping(Path(file_path), 'english')

                    # Build FFmpeg command for normalized transcoding
                    cmd = [
                        self.ffmpeg_bin,
                        '-hide_banner',
                        '-loglevel', 'error',

                        # Input with seek
                        '-ss', str(seek_ms / 1000.0),
                        '-i', file_path,
                        '-t', str(duration_ms / 1000.0),

                        # Stream mapping (includes video and selected audio track)
                        *audio_mapping,

                        # VIDEO: Normalize to H.264 1080p 30fps CBR
                        '-c:v', 'libx264',
                        '-preset', 'ultrafast',  # Fast encoding
                        '-b:v', '5000k',         # CBR video bitrate (5 Mbps)
                        '-maxrate', '5000k',     # Max bitrate
                        '-bufsize', '10000k',    # Buffer size for rate control
                        '-g', '60',              # Keyframe every 2 seconds (60 frames at 30fps)
                        '-keyint_min', '60',     # Minimum keyframe interval
                        '-sc_threshold', '0',    # Disable scene change detection
                        '-vf', 'scale=1920:1080,setsar=1,fps=30',  # Force exact 1080p, square pixels, 30fps
                        '-aspect', '16:9',  # Force 16:9 display aspect ratio

                        # AUDIO: Normalize to AAC stereo 48kHz
                        '-c:a', 'aac',
                        '-b:a', '192k',
                        '-ac', '2',
                        '-ar', '48000',

                        # Output as MPEG-TS with CBR
                        '-f', 'mpegts',
                        '-mpegts_flags', 'resend_headers',  # Resend PAT/PMT for stability
                        '-muxrate', '5400k',  # CBR prevents buffering ahead
                        'pipe:1'
                    ]

                    try:
                        # Spawn FFmpeg
                        proc = subprocess.Popen(
                            cmd,
                            stdout=subprocess.PIPE,
                            stderr=subprocess.PIPE
                        )

                        # Mark that we've started the first program
                        if first_program:
                            first_program = False

                        # Write MPEG-TS to FIFO (feeds broadcast FFmpeg)
                        bytes_written = 0
                        chunk_size = 188 * 50  # MPEG-TS packet alignment

                        while True:
                            chunk = proc.stdout.read(chunk_size)
                            if not chunk:
                                break
                            fifo.write(chunk)
                            bytes_written += len(chunk)

                        proc.wait()
                        print(f"[STUDIO] Ch{channel_number} prog#{current_index}: Completed ({bytes_written / 1024 / 1024:.1f} MB written)")

                    except BrokenPipeError:
                        print(f"[STUDIO] Ch{channel_number}: Broadcast FFmpeg disconnected, stopping studio")
                        break

                    except Exception as e:
                        print(f"[STUDIO] Ch{channel_number} prog#{current_index}: Error - {e}")
                        # Write error screen and continue
                        self.write_error_screen(fifo, duration=10, message=f"Error: {e}")

                    current_index += 1

        except Exception as e:
            print(f"[STUDIO] Ch{channel_number}: Fatal error - {e}")
        finally:
            print(f"[STUDIO] Ch{channel_number}: Studio thread exiting")

    def write_error_screen(self, fifo, duration: int = 10, message: str = "Please Stand By"):
        """
        Generate error screen (black + silent audio) when studio encounters error.
        Writes to FIFO to keep stream alive instead of crashing.

        Args:
            fifo: Open file handle to FIFO
            duration: Duration of error screen in seconds
            message: Error message (currently not overlayed, but could be with drawtext filter)
        """
        cmd = [
            self.ffmpeg_bin,
            '-hide_banner',
            '-loglevel', 'error',

            # Black screen
            '-f', 'lavfi',
            '-i', f'color=c=black:s=1920:1080:r=30:d={duration}',

            # Silent audio
            '-f', 'lavfi',
            '-i', f'anullsrc=r=48000:cl=stereo',

            # Duration
            '-t', str(duration),

            # Encode
            '-c:v', 'libx264',
            '-preset', 'ultrafast',
            '-c:a', 'aac',

            # Output
            '-f', 'mpegts',
            'pipe:1'
        ]

        try:
            proc = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.DEVNULL)
            chunk_size = 188 * 50

            while True:
                chunk = proc.stdout.read(chunk_size)
                if not chunk:
                    break
                fifo.write(chunk)

            proc.wait()
            print(f"[STUDIO] Wrote {duration}s error screen: {message}")

        except Exception as e:
            print(f"[STUDIO] Failed to write error screen: {e}")

    def broadcast_error_screen(self, broadcast_tower: BroadcastTower, duration: int = 10, message: str = "Please Stand By"):
        """
        Generate error screen (black + silent audio) when studio encounters error.
        Keeps broadcast alive instead of going off-air.

        Args:
            broadcast_tower: BroadcastTower to send signal to
            duration: Duration of error screen in seconds
            message: Error message (currently not overlayed, but could be with drawtext filter)
        """
        cmd = [
            self.ffmpeg_bin,
            '-hide_banner',
            '-loglevel', 'error',

            # Black screen
            '-f', 'lavfi',
            '-i', f'color=c=black:s=1920x1080:r=30:d={duration}',

            # Silent audio
            '-f', 'lavfi',
            '-i', f'anullsrc=r=48000:cl=stereo',

            # Duration
            '-t', str(duration),

            # Encode
            '-c:v', 'libx264',
            '-preset', 'ultrafast',
            '-c:a', 'aac',

            # Output
            '-f', 'mpegts',
            'pipe:1'
        ]

        try:
            proc = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.DEVNULL)
            chunk_size = 188 * 50

            while True:
                chunk = proc.stdout.read(chunk_size)
                if not chunk:
                    break
                broadcast_tower.broadcast(chunk)

            proc.wait()
            print(f"[STUDIO] Broadcast {duration}s error screen: {message}")

        except Exception as e:
            print(f"[STUDIO] Failed to broadcast error screen: {e}")

    def broadcast_transition_frame(self, broadcast_tower: BroadcastTower):
        """
        Send brief single-frame transition to keep stream alive between programs.
        Prevents HTTP connection timeout during FFmpeg process changes.
        """
        cmd = [
            self.ffmpeg_bin,
            '-hide_banner',
            '-loglevel', 'error',

            # Single black frame
            '-f', 'lavfi',
            '-i', 'color=c=black:s=1920x1080:r=30',
            '-f', 'lavfi',
            '-i', 'anullsrc=r=48000:cl=stereo',

            # Just 1 frame worth of data (~33ms)
            '-frames:v', '1',
            '-t', '0.033',

            # Match main stream encoding
            '-c:v', 'libx264',
            '-preset', 'ultrafast',
            '-b:v', '5000k',
            '-maxrate', '5000k',
            '-bufsize', '10000k',
            '-vf', 'scale=1920:1080,setsar=1,fps=30',
            '-aspect', '16:9',

            '-c:a', 'aac',
            '-b:a', '192k',
            '-ac', '2',
            '-ar', '48000',

            # MPEG-TS output
            '-f', 'mpegts',
            '-mpegts_flags', 'resend_headers',
            '-muxrate', '5400k',
            '-muxdelay', '0',
            '-muxpreload', '0',
            'pipe:1'
        ]

        try:
            proc = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.DEVNULL)
            chunk_size = 188 * 50

            while True:
                chunk = proc.stdout.read(chunk_size)
                if not chunk:
                    break
                broadcast_tower.broadcast(chunk)

            proc.wait()

        except Exception as e:
            print(f"[STUDIO] Failed to broadcast transition frame: {e}")

    # ============================================================================
    # CLIENT SUBSCRIPTION (MULTI-CLIENT SUPPORT)
    # ============================================================================

    def connect_client(self, channel_number: int, client_id: str):
        """
        Connect client antenna to channel's broadcast tower.

        Multiple clients can connect simultaneously to same channel.
        Each client gets their own antenna with minimal signal buffer.

        Args:
            channel_number: Channel number to connect to
            client_id: Unique identifier for this client (for logging/tracking)

        Returns:
            Antenna iterator that yields MPEG-TS chunks

        Raises:
            ValueError: If channel doesn't exist or isn't ready
        """
        if channel_number not in self.broadcast_towers:
            raise ValueError(f"Channel {channel_number} not ready")

        broadcast_tower = self.broadcast_towers[channel_number]
        antenna = broadcast_tower.connect_antenna(client_id)

        print(f"[UNLOADING_DOCK] Client {client_id} antenna connected to channel {channel_number}")
        return antenna

    # ============================================================================
    # CHANNEL LIFECYCLE MANAGEMENT
    # ============================================================================

    def ensure_channel_ready(self, channel_number: int, channel_data: dict):
        """
        Ensure channel has FIFO, BroadcastTower, studio thread, and broadcast FFmpeg running.

        Lifecycle:
        - Studio FIFO: Created once, persistent
        - Studio thread: Started once, writes to FIFO continuously
        - BroadcastTower: Created once, persistent
        - Broadcast FFmpeg: Started when first client connects, reads FIFO → feeds tower

        Returns:
            BroadcastTower for this channel
        """
        # Create BroadcastTower if not exists
        if channel_number not in self.broadcast_towers:
            tower = self.create_broadcast_tower(channel_number)
            self.broadcast_towers[channel_number] = tower
        else:
            tower = self.broadcast_towers[channel_number]

        # Create studio FIFO if not exists
        if channel_number not in self.studio_fifos:
            fifo_path = self.create_studio_fifo(channel_number)
            self.studio_fifos[channel_number] = fifo_path
        else:
            fifo_path = self.studio_fifos[channel_number]

        # Start studio thread if not already running
        if channel_number not in self.active_studios or not self.active_studios[channel_number].is_alive():
            # If studio died, need to recreate FIFO and tower
            if channel_number in self.studio_fifos:
                print(f"[UNLOADING_DOCK] Studio died, recreating FIFO and BroadcastTower for channel {channel_number}")
                del self.studio_fifos[channel_number]
                fifo_path = self.create_studio_fifo(channel_number)
                self.studio_fifos[channel_number] = fifo_path

                tower = self.create_broadcast_tower(channel_number)
                self.broadcast_towers[channel_number] = tower

            thread = threading.Thread(
                target=self.build_stream,
                args=(channel_data, fifo_path),
                daemon=True,
                name=f"Studio-Ch{channel_number}"
            )
            thread.start()
            self.active_studios[channel_number] = thread
            print(f"[UNLOADING_DOCK] Started studio for channel {channel_number}")
        else:
            print(f"[UNLOADING_DOCK] Studio already running for channel {channel_number}")

        # Start broadcast FFmpeg if not running (reads from FIFO, feeds tower)
        if channel_number not in self.broadcast_ffmpegs:
            self.start_broadcast_ffmpeg(channel_number, fifo_path, tower)
        else:
            # Check if still alive
            proc = self.broadcast_ffmpegs.get(channel_number)
            if proc and proc.poll() is not None:
                # Dead, restart
                print(f"[UNLOADING_DOCK] Broadcast FFmpeg died for channel {channel_number}, restarting")
                self.start_broadcast_ffmpeg(channel_number, fifo_path, tower)

        return tower

    # ============================================================================
    # OUTPUT WRAPPER (delegate to FactoryFloor)
    # ============================================================================

    def get_master_playlist(self, external_url: str) -> str:
        """Generate master M3U playlist (all channels)."""
        return self.factory_floor.generate_playlist(external_url)

    def get_xmltv_guide(self) -> str:
        """Generate XMLTV EPG guide."""
        return self.factory_floor.generate_xmltv()

    def get_lineup_json(self, request_host: str) -> list:
        """Generate HDHomeRun lineup.json."""
        return self.factory_floor.generate_lineup_json(request_host)

    # ============================================================================
    # CHANNEL DATA ACCESS (delegate to FactoryFloor)
    # ============================================================================

    def get_channel(self, channel_number: int) -> Optional[dict]:
        """Get channel data by number."""
        return self.factory_floor.channels.get(str(channel_number))

    def get_all_channels(self) -> list:
        """Get all channels as list."""
        return [
            data
            for _, data in sorted(self.factory_floor.channels.items(), key=lambda item: int(item[0]))
        ]

    def get_channel_count(self) -> int:
        """Get count of active channels."""
        return len(self.factory_floor.channels)

    # ============================================================================
    # STATUS
    # ============================================================================

    def get_status(self) -> dict:
        """
        Get UnloadingDock status.

        Returns:
            Status dict with studio threads and broadcast tower info
        """
        tower_stats = {}
        for ch, tower in self.broadcast_towers.items():
            tower_stats[ch] = tower.get_stats()

        return {
            "active_channels": len(self.active_studios),
            "broadcast_towers": len(self.broadcast_towers),
            "studios": {
                ch: thread.is_alive()
                for ch, thread in self.active_studios.items()
            },
            "tower_stats": tower_stats
        }
